// src/app/about/page.tsx
"use client";

import { useRouter } from "next/navigation";

export default function AboutPage() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Hero */}
      <div className="bg-blue-900 text-white py-12 px-4 text-center">
        <h1 className="text-3xl font-bold mb-3">About Ar‑Learn</h1>
        <p className="text-blue-100 max-w-2xl mx-auto">
          The intelligent school management and analytics platform designed specifically for Kenyan schools.
        </p>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-10 space-y-12">
        {/* What is Ar-Learn? */}
        <section>
          <h2 className="text-2xl font-bold text-gray-800 mb-4">What is Ar‑Learn?</h2>
          <p className="text-gray-600 leading-relaxed">
            Ar‑Learn is a complete, web‑based school management platform that combines everyday
            administrative tasks with advanced analytics and machine learning. It supports both
            the 8‑4‑4 and CBC curricula and is built to handle up to 100,000 students without
            slowing down. Teachers enter marks once, and the system automatically generates
            report cards, analytics, risk alerts, and professional AI‑powered remarks.
          </p>
        </section>

        {/* Main Engineering */}
        <section>
          <h2 className="text-2xl font-bold text-gray-800 mb-4">How It Works</h2>
          <div className="grid gap-6 md:grid-cols-2">
            <div className="bg-white p-6 rounded-xl shadow-sm">
              <h3 className="font-semibold text-lg mb-2">🧠 Analytics Engine</h3>
              <p className="text-gray-600">
                Pre‑computes school means, class ranks, teacher value‑add scores, and subject
                performance. Dashboards load instantly thanks to Redis caching.
              </p>
            </div>
            <div className="bg-white p-6 rounded-xl shadow-sm">
              <h3 className="font-semibold text-lg mb-2">🤖 Machine Learning</h3>
              <p className="text-gray-600">
                A predictive risk model trains silently on your data and warns you which
                students are likely to fail next term – before it happens.
              </p>
            </div>
            <div className="bg-white p-6 rounded-xl shadow-sm">
              <h3 className="font-semibold text-lg mb-2">📊 Role‑Based Dashboards</h3>
              <p className="text-gray-600">
                Separate, protected views for Headteachers, Deans, Class Teachers, Subject
                Teachers, and Parents – each seeing exactly what they need.
              </p>
            </div>
            <div className="bg-white p-6 rounded-xl shadow-sm">
              <h3 className="font-semibold text-lg mb-2">📄 Smart Report Cards</h3>
              <p className="text-gray-600">
                Customizable templates, one‑click PDF downloads, and direct printing.
                Professional remarks are automatically generated by the AI engine.
              </p>
            </div>
          </div>
        </section>

        {/* Why Best for Your School */}
        <section>
          <h2 className="text-2xl font-bold text-gray-800 mb-4">Why Ar‑Learn for Your School?</h2>
          <ul className="space-y-3 text-gray-600">
            <li>✅ <strong>Zero upfront cost</strong> – runs on free cloud services</li>
            <li>✅ <strong>Saves teachers hours</strong> – automated calculations, bulk entry, pre‑filled remarks</li>
            <li>✅ <strong>CBC ready</strong> – full competency tracking (EE, ME, AE, BE) per subject</li>
            <li>✅ <strong>Early warning system</strong> – rule‑based flags + ML predictions prevent failure</li>
            <li>✅ <strong>Parent engagement</strong> – secure portal for results, fees, and report cards</li>
            <li>✅ <strong>Scalable</strong> – designed for 100,000+ students without performance loss</li>
            <li>✅ <strong>Future‑proof</strong> – machine learning and AI already built in, improving every term</li>
          </ul>
        </section>

        {/* Advantages for Teachers & Students */}
        <section>
          <h2 className="text-2xl font-bold text-gray-800 mb-4">Advantages</h2>
          <div className="grid gap-6 md:grid-cols-2">
            <div className="bg-green-50 p-6 rounded-xl">
              <h3 className="font-semibold text-lg mb-2 text-green-800">👩‍🏫 For Teachers</h3>
              <ul className="text-green-700 space-y-2">
                <li>Enter marks and attendance in seconds</li>
                <li>Auto‑generated professional remarks</li>
                <li>One‑click report cards for their class</li>
                <li>Real‑time risk flags for struggling students</li>
                <li>View their own timetable and profile</li>
              </ul>
            </div>
            <div className="bg-purple-50 p-6 rounded-xl">
              <h3 className="font-semibold text-lg mb-2 text-purple-800">🎓 For Students & Parents</h3>
              <ul className="text-purple-700 space-y-2">
                <li>Early detection of academic struggles</li>
                <li>Specific, actionable intervention plans</li>
                <li>Parents view results and fees 24/7</li>
                <li>Download official report cards at home</li>
                <li>Clear, professional progress reports</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Data Protection */}
        <section>
          <h2 className="text-2xl font-bold text-gray-800 mb-4">How Your Data is Protected</h2>
          <div className="grid gap-4 md:grid-cols-2 text-gray-600">
            <div>🔒 <strong>Encryption:</strong> All data encrypted in transit (HTTPS) and at rest (AES‑256).</div>
            <div>🛡️ <strong>Access Control:</strong> Each role sees only what they’re allowed to see.</div>
            <div>🔑 <strong>Secure Login:</strong> Passwords hashed with bcrypt; tokens required for every API call.</div>
            <div>📦 <strong>Backups:</strong> Automatic daily backups with point‑in‑time recovery.</div>
            <div>🚫 <strong>No third‑party access:</strong> Your data never leaves your dedicated database.</div>
            <div>🧑‍💻 <strong>Audit trails:</strong> Every change is tracked (results submission, fee payments, etc.).</div>
          </div>
        </section>

        {/* FAQ */}
        <section>
          <h2 className="text-2xl font-bold text-gray-800 mb-4">Frequently Asked Questions</h2>
          <div className="space-y-4">
            <details className="bg-white p-4 rounded-xl shadow-sm">
              <summary className="font-semibold cursor-pointer">How many students can the system handle?</summary>
              <p className="mt-2 text-gray-600">It is designed for up to 100,000 students and can scale further with paid cloud plans.</p>
            </details>
            <details className="bg-white p-4 rounded-xl shadow-sm">
              <summary className="font-semibold cursor-pointer">Is there any cost to start?</summary>
              <p className="mt-2 text-gray-600">No. The free tiers of Render, Vercel, Supabase, and Upstash allow the entire platform to run at zero monthly cost.</p>
            </details>
            <details className="bg-white p-4 rounded-xl shadow-sm">
              <summary className="font-semibold cursor-pointer">What happens if the internet goes down?</summary>
              <p className="mt-2 text-gray-600">The frontend is cached in your browser; once loaded, many pages still work. Data syncs as soon as the connection returns.</p>
            </details>
            <details className="bg-white p-4 rounded-xl shadow-sm">
              <summary className="font-semibold cursor-pointer">Can we import historical results?</summary>
              <p className="mt-2 text-gray-600">Yes. The Dean can upload CSV/Excel files of previous terms' results for trend analysis.</p>
            </details>
            <details className="bg-white p-4 rounded-xl shadow-sm">
              <summary className="font-semibold cursor-pointer">Who can see a student's information?</summary>
              <p className="mt-2 text-gray-600">Only the school's staff (with role‑based limits) and the student's own parents (via a unique access code).</p>
            </details>
          </div>
        </section>

        {/* Back button */}
        <div className="text-center pb-10">
          <button
            onClick={() => router.back()}
            className="px-6 py-2 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700"
          >
            ← Back to Dashboard
          </button>
        </div>
      </div>
    </div>
  );
}